# Background and foreground colors
background = #010419
foreground = #E5DBBA

# Standard colors
palette = 0=#010419
palette = 1=#ff8b73
palette = 2=#61bc5c
palette = 3=#e7bc3f
palette = 4=#5582dc
palette = 5=#e762d2
palette = 6=#008e8e
palette = 7=#E5DBBA

# Bright colors
palette = 8=#67696f
palette = 9=#ffa686
palette = 10=#7ce762
palette = 11=#ffc800
palette = 12=#76a4ff
palette = 13=#ea79d7
palette = 14=#2fb5b5
palette = 15=#fae9a2
