$color = rgba(1, 4, 25, 1)
$inner_color = rgba(1, 4, 25, 0.66)
$outer_color = rgba(231, 98, 210, 1)
$font_color = rgba(229, 219, 186, 1)
$placeholder_color = rgba(229, 219, 186, 0.7)
$check_color = rgba(0, 142, 142, 1)
