background            #010419
foreground            #E5DBBA

# black
color0  #010419
color8  #67696f

# red
color1  #ff8b73
color9  #ffa686

# green
color2  #61bc5c
color10 #7ce762

# yellow
color3  #e7bc3f
color11 #ffc800

# blue
color4  #5582dc
color12 #76a4ff

# magenta
color5  #e762d2
color13 #ea79d7

#cyan
color6  #008e8e
color14 #2fb5b5

#white
color7  #E5DBBA
color15 #fae9a2


