# Extra autostart processes
# exec-once = uwsm-app -- my-service
exec-once = gnome-keyring-daemon --start --components=secrets,ssh
exec-once = uwsm app -- hyprsunset
exec-once = waybar 

# Automations
exec-one = ~/dotfiles/automations/bin/epoll_manager
exec-once = ~/dotfiles/scripts/hardwareListener.sh
