# Extra autostart processes
# exec-once = uwsm-app -- my-service
exec-once = gnome-keyring-daemon --start --components=secrets,ssh
exec-once = uwsm app -- hyprsunset
exec-once = waybar 

# Automations
exec-once = bash -c 'until busctl --user status >/dev/null 2>&1; do sleep 0.2; done; exec /home/luciano/dotfiles/automations/bin/epoll_manager'
exec-once = /home/luciano/dotfiles/scripts/hardwareListener.sh
